version: '3'
services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: aglomerados-frontend
    volumes:
       - ./front:/front
       - /front/node_modules
  
  backend:
    build:
      context: ./back/gerenciamento-aglomeracoes
      dockerfile: Dockerfile
    container_name: aglomerados-backend
    command: npm start
    volumes:
      - ./back/gerenciamento-aglomeracoes:/back/gerenciamento-aglomeracoes
      - /back/gerenciamento-aglomeracoes/node_modules
    ports:
      - "3030:3030"
