version: '3'
services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: aglomerados-frontend
    volumes:
       - ./front:/aglomerados/front
       - /aglomerados/front/node_modules