version: '3'
services:
  app:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    container_name: aglomerados-frontend
    volumes:
      #  - .:/front
       - /front/node_modules