version: '1'
services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: aglomerados-frontend
    volumes:
       - ./front:/aglomerados/front
       - /aglomerados/front/node_modules